### ISSUE TITLE
This is cool... but...

### ISSUE THREAD

**Issue by lookfirst** [SharperShape/wercker-step-cache#1]
Why not just do something like this... `-Dmaven.repo.local=${WERCKER_CACHE_DIR}`

I'm evaluating switching from circleci to wercker because circleci runs the save cache folder step too early and misses some things that get added. Sadly, there isn't any way around it.

**Comment by ernoaapa** [comment]
Hmm.. good idea. Not sure though does `sbt` have similar property?
Also in future I only need to update this step to add another build tool directory to be cached.

If using just maven, your suggestion would work.
